baseurl = "https://realhelpdoncaster.org/"
languageCode = "en-gb"
title = "Real Help Doncaster"
disableKinds = ["RSS", "taxonomy"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true