backend:
  name: git-gateway
  branch: doncaster

media_folder: "hugo/static/assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "hugo/content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title (Real Help Doncaster prepended)", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Pretitle (optional - white text above title)", name: "pretitle", widget: "string", required: false},
              {label: "Title (optional - yellow)", name: "title", widget: "string"},
              {label: "Subtitle (optional - white text below title)", name: "subtitle", widget: "string", required: false},
              {label: "Body (optional)", name: "body", widget: "markdown", required: false},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "What Is", name: "whatis", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]},
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: "Who", name: "who", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "How", name: "how", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "Partners", name: "partners", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "YouTube (embed URL - if set will hide image)", name: "youtube", widget: "string", required: false},
              {label: "Image (only set if no YouTube)", name: "image", widget: "image"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "List", name: "list", widget: "markdown"}
            ]}
      - file: "hugo/content/about-us/_index.md"
        label: "About Us"
        name: "about-us"
        fields:
          - {label: "Title (Real Help Doncaster prepended)", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Pretitle (optional - yellow text above title)", name: "pretitle", widget: "string", required: false},
              {label: "Title (optional - white)", name: "title", widget: "string", required: false},
            ]}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "First Paragraph", name: "firstpara", widget: "markdown"},
              {label: "Body", name: "body", widget: "markdown"},
            ]}
      - file: "hugo/content/how-it-works/_index.md"
        label: "How it Works"
        name: "how-it-works"
        fields:
          - {label: "Title (Real Help Doncaster prepended)", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Pretitle (optional - yellow text above title)", name: "pretitle", widget: "string", required: false},
              {label: "Title (optional - white)", name: "title", widget: "string", required: false},
              {label: "Subtitle (optional - white text below title)", name: "subtitle", widget: "string", required: false},
              {label: "Body (optional)", name: "body", widget: "markdown", required: false},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Where", name: "where", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Stat 1", name: "stat1", widget: "object", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Count", name: "count", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]},
              {label: "Stat 2", name: "stat2", widget: "object", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Count", name: "count", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]},
              {label: "Stat 3", name: "stat3", widget: "object", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Count", name: "count", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "How", name: "how", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Card 1", name: "card1", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Subheading", name: "subheading", widget: "string"},
                {label: "Body", name: "body", widget: "markdown"}
              ]},
              {label: "Card 2", name: "card2", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Subheading", name: "subheading", widget: "string"},
                {label: "Body", name: "body", widget: "markdown"}
              ]},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
      - file: "hugo/content/how-to-apply/_index.md"
        label: "How to Apply"
        name: "how-to-apply"
        fields:
          - {label: "Title (Real Help Doncaster prepended)", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Pretitle (optional - yellow text above title)", name: "pretitle", widget: "string", required: false},
              {label: "Title (optional - white)", name: "title", widget: "string", required: false},
              {label: "Subtitle (optional - white text below title)", name: "subtitle", widget: "string"},
              {label: "Body (optional)", name: "body", widget: "markdown", required: false},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Body", name: "content", widget: "markdown"}
          - {label: "List", name: "list", widget: "markdown"}
          - {label: "Partners", name: "partners", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "body", name: "body", widget: "markdown"}
            ]}
      - file: "hugo/content/get-involved/_index.md"
        label: "Get Involved"
        name: "get-involved"
        fields:
          - {label: "Title (Real Help Doncaster prepended)", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Pretitle (optional - yellow text above title)", name: "pretitle", widget: "string", required: false},
              {label: "Title (optional - white)", name: "title", widget: "string", required: false},
              {label: "Subtitle (optional - white text below title)", name: "subtitle", widget: "string"}, required: false,
              {label: "Body (optional)", name: "body", widget: "markdown", required: false},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Body", name: "content", widget: "markdown"}
          - {label: "Section", name: "section", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Image", name: "image", widget: "image"}
            ]}
      - file: "hugo/content/privacy/_index.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title (Real Help Doncaster prepended)", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Pretitle (optional - yellow text above title)", name: "pretitle", widget: "string", required: false},
              {label: "Title (optional - white)", name: "title", widget: "string", required: false},
              {label: "Subtitle (optional - white text below title)", name: "subtitle", widget: "string", required: false},
              {label: "Body (optional)", name: "body", widget: "markdown", required: false},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Body", name: "content", widget: "markdown"}
          - {label: "Partners", name: "partners", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
  - name: "global"
    label: "Global"
    editor:
      preview: false
    files:
      - file: "hugo/content/global/_footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Footer Title", name: "title", widget: "string"}
          - {label: "Row 1 (Share)", name: "row1", widget: "markdown"}
          - {label: "Row 2 (Link out)", name: "row2", widget: "markdown"}
          - {label: "Row 3 (Internal link)", name: "row3", widget: "markdown"}
          - {label: "Links", name: "links", widget: "markdown"}
